# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:
  context-path: /management
  health:
    mail:
      enabled: false # When using the MailService, configure an SMTP server and set this to true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: sprint
  profiles:
    # The commented value for `active` can be replaced with valid spring profiles to load.
    # Otherwise, it will be filled in by maven when building the WAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  jackson:
    serialization.write_dates_as_timestamps: false
  jpa:
    database-platform: it.cnr.si.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    #    database: H2
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.cache.region.factory_class: it.cnr.si.config.hazelcast.HazelcastCacheRegionFactory
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true
  print:
    rimborso: /missioni/RimborsoMissione.jrxml
    ordine: /missioni/OrdineMissione.jrxml
    anticipo: /missioni/OrdineMissioneAnticipo.jrxml
    autoPropria: /missioni/OrdineMissioneAutoPropria.jrxml
    taxi: /missioni/OrdineMissioneTaxi.jrxml
    autoNoleggio: /missioni/OrdineMissioneAutoNoleggio.jrxml
    endpoint: http://sigla-print.test.si.cnr.it/api/v1/get/print
  messages:
    basename: i18n/messages
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    mode: XHTML
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 10Mb
  mail:
    messages:
      erroreGenerico:
        oggetto: Missioni. Errore Generico.
      erroreLetturaFlussoOrdine:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per l'ordine di missione
      erroreLetturaFlussoAnnullamento:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Annullamento Ordine da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per l'annullamento dell'ordine di missione
      erroreLetturaFlussoRimborso:
        oggetto: Missioni. Errore durante l'aggiornamento del Rimborso da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per il rimborso missione
      erroreComunicazioneRimborsoSigla:
        oggetto: Missioni. Errore durante la comunicazione a SIGLA del Rimborso Missione.
        testo: Si segnala che la comunicazione a SIGLA del rimborso missione
      erroreBypassStepRespGruppo:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine per il bypass del responsabile del gruppo.
        testo: Si segnala che l'aggiornamento per il bypass del responsabile del gruppo dell'ordine di missione
      erroreBypassStepAmm:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine per il bypass degli amministrativi.
        testo: Si segnala che l'aggiornamento per il bypass degli amministrativi dell'ordine di missione
      invioResponsabileGruppo:
        oggetto: Autorizzazione Ordine di Missione di
      invioOrdinePerValidazioneDatiFinanziari:
        oggetto: Verifica Ordine di Missione di
      invioAnnullamentoOrdineMissione:
        oggetto: Richiesta Annullamento Ordine di Missione di
      invioAnnullamentoRimborsoMissione:
        oggetto: Richiesta Annullamento Rimborso Missione di
      invioRimborsoPerValidazioneDatiFinanziari:
        oggetto: Verifica Rimborso Missione di
      ritornoOrdineMissioneMittente:
        oggetto: Ordine di Missione reinviato al mittente.
      ritornoAnnullamentoOrdineMittente:
        oggetto: Annullamento Ordine di Missione reinviato al mittente.
      ritornoMissioneMittente:
        oggetto: Rimborso Missione reinviato al mittente.
      approvazioneAnticipo:
        oggetto: Anticipo su Ordine di Missione.
      importoMissionePerResponsabileGruppo:
        oggetto: Comunicazione Importo Rimborso Missione di
      approvazioneOrdineMissione:
        oggetto: Ordine di Missione approvato.
      approvazioneRimborsoMissione:
        oggetto: Rimborso Missione approvato.
      approvazioneAnnullamentoOrdineMissione:
        oggetto: Annullamento Ordine di Missione.
      annullamentoRimborsoMittente:
        oggetto: Annullamento Rimborso Missione
    host: smtp.cnr.it
    protocol: smtp
    port: 25
    from: missioni@cnr.it
    tls: false
    auth: false
    send.error.to: missioni@cnr.it

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./DB-H2/misioni;DB_CLOSE_DELAY=-1
    name: missioni
    username: missioni
    password: missionipw

  proxy:
    SIGLA:
      url: http://localhost:8080/SIGLA/
      context:
        cd_unita_organizzativa: "ZZZ.ZZZ"
        cd_cds: "ZZZ"
        cd_cdr: "ZZZ.ZZZ.ZZZ"

security:
  basic:
    enabled: false

cache:
  hazelcast.packages: it.cnr.si.missioni.domain.*,it.cnr.si.missioni.service.*
  init_cache: true

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
    #allowed-origins: "*"
    #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
    #allowed-headers: "*"
    #exposed-headers:
    #allow-credentials: true
    #max-age: 1800
  mail:
    from: sprint@localhost
  security:
    authentication:
      oauth:
        clientid: sprintapp
        secret: mySecretOAuthSecret
        tokenValidityInSeconds: 1800
  swagger:
    title: sprint API
    description: sprint API documentation
    version: 0.0.1
    termsOfServiceUrl:
    contactName:
    contactUrl:
    contactEmail:
    license:
    licenseUrl:
  ribbon:
    # comma seperated list of profiles to show a ribbon on the GUI
    displayOnActiveProfiles: dev

cache.hazelcast:
  name: sprint-missioni
  members: 127.0.0.1

storage:
  maxItemsPerPage: 10
  folder_path: /Comunicazioni al CNR/Missioni
  folder_path_config: /Config
  folder_path_manual: /Config/Manuali


ajp:
  port: 8009
  timeout: 120000


server:
  port: 8080

logging.config: classpath:logback-local.xml

cnr:
  ajp:
    port: 8009
    timeout: 120000
  cache:
    hazelcast:
      packages: it.cnr.si.missioni
  storage:
    driver: filesystem
    filesystem:
      directory: /tmp

keycloak:
  enabled: false
