
spring:
  config:
    file:
      pathFileConfigJson: C:\Users\mirra_davide\Desktop\JAVA\ISS\sprint-missioni-config\sprint-missioni-config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@oracledb-coll.iss.it:1521/COLL.ISS.IT
    name: missioni
    username: MISSIONICOLL
    password: MISSIONICOLLPSW
  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: ORACLE
    show-sql: false
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: it.cnr.si.config.hazelcast.HazelcastCacheRegionFactory
      hibernate.cache.use_minimal_puts: true
      hibernate.cache.hazelcast.use_lite_member: true

  ldap:
    enabled: true
    userSearchBase: Dc=iss,dc=it
    userSearchFilter: (&(objectCategory=Person)(userPrincipalName={0}))
    url: ldap://iss.it:389
    managerDn: liferayuser@iss.it
    managerPassword: G2wHrKqHGE
    change.password.url: https://utenti.iss.it
    attrName: givenname
    attrSurname: sn
    attrMail:
  proxy:
    SIGLA:
      url: http://sigla-t:8080/SIGLA/
      username: ente
      password: 2023enteiss
      context:
        cd_unita_organizzativa: "999.000"
        cd_cds: "999"
        cd_cdr: "999.000.000"
  mail:
    messages:
      erroreGenerico:
        oggetto: Missioni. Errore Generico.
      erroreLetturaFlussoOrdine:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per l'ordine di missione
      erroreLetturaFlussoAnnullamento:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Annullamento Ordine da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per l'annullamento dell'ordine di missione
      erroreLetturaFlussoRimborso:
        oggetto: Missioni. Errore durante l'aggiornamento del Rimborso da Scrivania Digitale.
        testo: Si segnala che il recupero delle informazioni dalla scrivania digitale per il rimborso missione
      erroreComunicazioneRimborsoSigla:
        oggetto: Missioni. Errore durante la comunicazione a SIGLA del Rimborso Missione.
        testo: Si segnala che la comunicazione a SIGLA del rimborso missione
      erroreBypassStepRespGruppo:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine per il bypass del responsabile del gruppo.
        testo: Si segnala che l'aggiornamento per il bypass del responsabile del gruppo dell'ordine di missione
      erroreBypassStepAmm:
        oggetto: Missioni. Errore durante l'aggiornamento dell'Ordine per il bypass degli amministrativi.
        testo: Si segnala che l'aggiornamento per il bypass degli amministrativi dell'ordine di missione
      invioResponsabileGruppo:
        oggetto: Autorizzazione Ordine di Missione di
      invioOrdinePerValidazioneDatiFinanziari:
        oggetto: Verifica Ordine di Missione di
      invioAnnullamentoOrdineMissione:
        oggetto: Richiesta Annullamento Ordine di Missione di
      invioAnnullamentoRimborsoMissione:
        oggetto: Richiesta Annullamento Rimborso Missione di
      invioRimborsoPerValidazioneDatiFinanziari:
        oggetto: Verifica Rimborso Missione di
      ritornoOrdineMissioneMittente:
        oggetto: Ordine di Missione reinviato al mittente.
      ritornoAnnullamentoOrdineMittente:
        oggetto: Annullamento Ordine di Missione reinviato al mittente.
      ritornoMissioneMittente:
        oggetto: Rimborso Missione reinviato al mittente.
      approvazioneAnticipo:
        oggetto: Anticipo su Ordine di Missione.
      importoMissionePerResponsabileGruppo:
        oggetto: Comunicazione Importo Rimborso Missione di
      approvazioneOrdineMissione:
        oggetto: Ordine di Missione approvato.
      approvazioneRimborsoMissione:
        oggetto: Rimborso Missione approvato.
      approvazioneAnnullamentoOrdineMissione:
        oggetto: Annullamento Ordine di Missione.
      annullamentoRimborsoMittente:
        oggetto: Annullamento Rimborso Missione
    host: extmail.iss.it
    protocol: smtp
    port: 25
    from: missioni@iss.it
    username: liferaymail@iss.it
    password: J!#Gm[>fQy*8AE;2
    tls: true
    auth: true
    send.error.to: ciro.salvio@iss.it
  print:
    endpoint: http://sigla-t:8082/api/v1/get/print
    rimborso: /missioni/iss/RimborsoMissione.jrxml
    ordine: /missioni/iss/OrdineMissione.jrxml
    anticipo: /missioni/iss/OrdineMissioneAnticipo.jrxml
    autoPropria: /missioni/iss/OrdineMissioneAutoPropria.jrxml
    taxi: /missioni/iss/OrdineMissioneTaxi.jrxml
    autoNoleggio: /missioni/iss/OrdineMissioneAutoNoleggio.jrxml

audit: false

management:
  auditevents:
    enabled: false

user:
  admin:
    username: ${spring.proxy.vecchiaScrivania.username}
    password: ${spring.proxy.vecchiaScrivania.password}


flows:
  test: true
  type: HAPPPYSIGN
  url: https://isscol.happysign.it:8443/HappySignRest/rest/HappySignRest/
  username: auto@iss
  password: P@sswordprimoaccess0
  organizzation: iss
  keystore:
    path: C:\Users\mirra_davide\Desktop\JAVA\ISS\sprint-missioni-config\sprint-missioni-config\isscol_client.p12
    password: password
  autorizzazione:
    progdifuo: duilioapp
    progstessauo: duilioapp
    noprogdifuo: duilioapp
    dirgae: duilioapp
    gae: duilioapp
    dirgen: duilioapp
    nocaricoente: duilioapp
    p_dirigenti: duilioapp
    vocipresidente: duilioapp

  rimborso:
    default:
      template : duilioapp
      signSiglaUo : DRUE

codiciUo:
  presidenza: 000.033
  direzioneGenerale: 000.031
  drue: 000.000

keyUo:
  presidenza: 14
  direzioneGenerale: 6
  direzione: 7

storage:
  maxItemsPerPage: 10
  folder_path: /Comunicazioni a ISS/Missioni
  folder_path_config: /Config
  folder_path_manual: /Config/Manuali

cache:
  init_cache: true

logging.config: classpath:logback-local.xml

aceiss:
  url: https://webapi.iss.it/anag/

authJWT:
  urlToken: https://login.microsoftonline.com/cf30c7fd-6616-4b62-ad83-b574b27d5912/
  scopes: api://anag.iss.it/.default
  clientId: 0603aa0e-ce6f-48f3-9e67-b0783b22e8e3
  secret: .MV8Q~Lc1fUkZx.XiJLELrLZwq-fgaoPzJwS0a8p

cron:
  comunicaDati:
    name: comunicaDati
    active: true
    cronExpression: "0 0 4 * * MON-SAT"

  comunicaDatiVecchiaScrivania:
    name: comunicaDatiVecchiaScrivania
    active: true
    cronExpression: "0 0 5 * * MON-SAT"

  evictCache:
    name: evictCache
    active: false
    cronExpression: "0 0 2 * * MON-SAT"

  loadCache:
    name: loadCache
    active: false
    cronExpression: "0 0 3 * * MON-SAT"

  verifyStep:
    name: verifyStep
    active: false
    cronExpression: "0 */1 * * * MON-SAT"

  happysign:
    name: happysign
    active: true
    cronExpression: "0 */1 * ? * *"

jhipster:
  mail:
    from: missioni@cnr.it
  security:
    authentication:
      oauth:
        clientid: sprintapp
        secret: mySecretOAuthSecret
        # Token is valid 30 minutes
        tokenValidityInSeconds: 1800
  ribbon:
    # comma seperated list of profiles to show a ribbon on the GUI
    displayOnActiveProfiles: test



cache.hazelcast:
  name: sprint-missioni
  members: 127.0.0.1

server:
  port: 8088

cnr:
  ajp:
    port: 8009
    timeout: 120000
  cache:
    hazelcast:
      packages: it.cnr.si.missioni
  storage:
    driver: AZURE
    azure:
      connectionString: cnr.azure.connectionString=DefaultEndpointsProtocol=http;AccountName=siglatest;AccountKey=3Zcx/A0zAPamRChFifloCkadNE09rPG94qRssq7G+Wnu+6ng0XcY03qTu6OKy6opyRSg9pCu8RFAxvM3ywBhlg==;EndpointSuffix=core.windows.net
      containerName: sigla-coll-main-storage
    path:
      comunicazioni:
        dal: /Comunicazioni da ISS
        al: /Comunicazioni a ISS

keycloak:
  enabled: false
