name: Publish package to GitHub Packages
on:
  push:
    branches: [master, jdk21+docker]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build and deploy SNAPSHOT
        run: |
          mvn clean deploy \
            -s .m2/settings.xml \
            -P AZURE \
            -DskipTests \
            --batch-mode --errors --fail-at-end --show-version
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.ISS_PAT }}

