name: Release Packages
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set release version
        run: |
          mvn -B versions:set \
            -DnewVersion=${{ github.event.release.tag_name }} \
            -DgenerateBackupPoms=false
      - name: Deploy release
        run: |
          mvn clean deploy \
            -s .m2/settings.xml \
            -P AZURE \
            -DskipTests \
            --batch-mode --errors --fail-at-end --show-version
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set next SNAPSHOT version
        run: |
          mvn -B versions:set \
            -DnewVersion=${{ github.event.release.tag_name }}-SNAPSHOT \
            -DgenerateBackupPoms=false
      - name: Commit and push changes
        run: |
          git config --global user.email "dirgensa@iss.it"
          git config --global user.name "dirgensa"
          git commit -am "Bumped version to ${{ github.event.release.tag_name }}"
          git push
